### ISSUE TITLE
Card Data as json

### ISSUE THREAD

**Issue by Lalman888** [jayk-gupta/Code-Nexus#1]
We can add card data as json 
![image](https://user-images.githubusercontent.com/90516185/235294477-a358da4e-e029-4c07-8bc1-9d41ef6465dc.png)

**Comment by priyankarpal** [comment]
> We can add card data as json ![image](https://user-images.githubusercontent.com/90516185/235294477-a358da4e-e029-4c07-8bc1-9d41ef6465dc.png)

yeah we're currently working on it
