### ISSUE TITLE
The beauty of favicon is missing in the website. 

### ISSUE THREAD

**Issue by Parthmandale** [jayk-gupta/Code-Nexus#30]
I'll add Favicon to the website which is there in most of the website!

The favicon I will add will be matching to existing design of the website.

will add a screenshot when I'll create PR.

**Comment by priyankarpal** [comment]
could you add a clear description?

**Comment by Parthmandale** [comment]
@priyankarpal I've added the description, you can now assign me this issue.

**Comment by priyankarpal** [comment]
> @priyankarpal I've added the description, you can now assign me this issue.

done

**Comment by jayk-gupta** [comment]
Okay, add one and share it.

**Comment by Parthmandale** [comment]
@jayk-gupta , I have put the PR for it.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
