### ISSUE TITLE
#Selecting Multiple tags 

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [jayk-gupta/Code-Nexus#32]
### It would be more interactive if we could select multiple tags while sorting projects based on technology.

**Comment by priyankarpal** [comment]
assigned to you

**Comment by SoundaryaKoutharapu** [comment]
@priyankarpal could you please assign this issue to someone, as I am on learning stage of react.

**Comment by jayk-gupta** [comment]
> @priyankarpal could you please assign this issue to someone, as I am on learning stage of react.

Okay!
