### ISSUE TITLE
center image

### ISSUE THREAD

**Issue by MukeshOdhano** [jayk-gupta/Code-Nexus#33]
# Description
images were not center 

### BEFORE
![Before](https://user-images.githubusercontent.com/126863895/236665631-f948a868-2d21-4851-9805-83aa640d8d51.png)

### AFTER
![screencapture-localhost-5173-2023-05-07-13_05_29](https://user-images.githubusercontent.com/126863895/236665566-c8e1c745-b46e-405d-9afa-11a830c1c264.png)

**Comment by ankitxcoding** [comment]
I want to work on this.

**Comment by priyankarpal** [comment]
@MukeshOdhano do you want to work on this issue?

**Comment by MukeshOdhano** [comment]
@priyankarpal  i solved the issue but, i don't know why but i am having problem with pulling request

**Comment by priyankarpal** [comment]
> @priyankarpal i solved the issue but, i don't know why but i am having problem with pulling request

could you share the problem?

**Comment by MukeshOdhano** [comment]
@priyankarpal 
![image](https://user-images.githubusercontent.com/126863895/236719664-73838c4f-10f5-478d-965d-90aa2ed59c11.png)

**Comment by priyankarpal** [comment]
> @priyankarpal ![image](https://user-images.githubusercontent.com/126863895/236719664-73838c4f-10f5-478d-965d-90aa2ed59c11.png)

don't worry We will check

**Comment by MukeshOdhano** [comment]
@priyankarpal should i send pull request again?

**Comment by priyankarpal** [comment]
> @priyankarpal should i send pull request again?

nope you have created already

**Comment by priyankarpal** [comment]
> > @priyankarpal should i send pull request again?
> 
> nope you have created already

just check the PR comment I requested a changes

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by MukeshOdhano** [comment]
> Completed. Thanks for your contributions 🎉 ❤️

Is there any open source project for contribution?

**Comment by priyankarpal** [comment]
> > Completed. Thanks for your contributions tada heart
> 
> Is there any open source project for contribution?

I created a list of all Open Source projects you can check https://github.com/stars/priyankarpal/lists/open-source-projects
