### ISSUE TITLE
docs: we need to create documentation 

### ISSUE THREAD

**Issue by priyankarpal** [jayk-gupta/Code-Nexus#5]
- modify the README.md file
 - add contributing.md file

**Comment by jayk-gupta** [comment]
Readme is modified!
Will add contributing.md file

**Comment by me-imfhd** [comment]
@jayk-gupta can i make the contributing.md file more elaborate , like adding codes on how to clone and how to create new branch and more... assign me this

**Comment by me-imfhd** [comment]
you can just tell me should i work on this or you are fine by from your side

**Comment by priyankarpal** [comment]
> @jayk-gupta @priyankarpal can i make the contributing.md file more elaborate , like adding codes on how to clone and how to create new branch and more... assign me this

Ok work on it

**Comment by priyankarpal** [comment]
@me-imfhd could you share your progress on this issue?

**Comment by me-imfhd** [comment]
i will be sharing it by tommorow and within two days i will aim to complete it and make the PR

**Comment by me-imfhd** [comment]
@priyankarpal  Contributing.md file updated and made the PR... but it is showing a cross.... i do not get it... is the PR successful?

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
